import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

/** Cart UI aligned with storefront mock (greens, PayPal yellow, link blue) */
export const cartColors = {
  primaryGreen: '#2E7D32',
  primaryGreenDark: '#1B5E20',
  paypalYellow: '#FFC439',
  paypalBlue: '#003087',
  linkBlue: '#0056b3',
  divider: '#E0E0E0',
  muted: '#757575',
  noteSectionBg: '#F5F5F5',
} as const;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: cartColors.divider,
  },
  headerSide: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textDark,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: cartColors.divider,
  },
  heroArt: {
    width: 88,
    height: 88,
    borderRadius: 6,
    backgroundColor: '#E3F2FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  heroTextBlock: {
    flex: 1,
  },
  heroTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textDark,
  },
  heroSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: cartColors.muted,
    lineHeight: 20,
  },
  continueLink: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: '600',
    color: cartColors.linkBlue,
    textDecorationLine: 'underline',
  },
  lineWrap: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: cartColors.divider,
    flexDirection: 'row',
  },
  lineImage: {
    width: 80,
    height: 80,
    borderRadius: 6,
    backgroundColor: '#EEEEEE',
  },
  lineMain: {
    flex: 1,
    marginLeft: 12,
  },
  lineTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  lineTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
  },
  linePrice: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
  },
  lineVariant: {
    marginTop: 4,
    fontSize: 13,
    color: cartColors.muted,
  },
  quantityBox: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: cartColors.divider,
    borderRadius: 3,
    overflow: 'hidden',
  },
  qtyBtn: {
    width: 36,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  qtyBtnBorder: {
    borderRightWidth: 1,
    borderRightColor: cartColors.divider,
  },
  qtyBtnBorderLeft: {
    borderLeftWidth: 1,
    borderLeftColor: cartColors.divider,
  },
  qtyValue: {
    minWidth: 36,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
  },
  lineActions: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionLink: {
    fontSize: 14,
    fontWeight: '600',
    color: cartColors.linkBlue,
  },
  actionSep: {
    marginHorizontal: 10,
    fontSize: 14,
    color: cartColors.divider,
  },
  noteSection: {
    backgroundColor: cartColors.noteSectionBg,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 4,
  },
  noteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  noteInput: {
    flex: 1,
    height: 44,
    borderRadius: 5,
    paddingHorizontal: 12,
    backgroundColor: colors.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: cartColors.divider,
    fontSize: 15,
    color: colors.textDark,
  },
  noteApply: {
    height: 44,
    paddingHorizontal: 18,
    borderRadius: 5,
    backgroundColor: cartColors.primaryGreenDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteApplyText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
  },
  summaryBlock: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 8,
  },
  summaryHeading: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 14,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 15,
    color: colors.textDark,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textDark,
  },
  shippingRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shippingHint: {
    fontSize: 15,
    color: cartColors.linkBlue,
  },
  totalRow: {
    marginTop: 8,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: cartColors.divider,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textDark,
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textDark,
  },
  checkoutBlock: {
    paddingHorizontal: 16,
    paddingTop: 20,
    gap: 12,
  },
  checkoutGradient: {
    borderRadius: 6,
    overflow: 'hidden',
  },
  checkoutBtnInner: {
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkoutBtnText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '800',
  },
  orText: {
    textAlign: 'center',
    fontSize: 13,
    color: cartColors.muted,
    marginVertical: 4,
  },
  paypalBtn: {
    height: 50,
    borderRadius: 6,
    backgroundColor: cartColors.paypalYellow,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  paypalMark: {
    fontSize: 22,
    fontWeight: '800',
    fontStyle: 'italic',
    color: cartColors.paypalBlue,
    letterSpacing: -0.5,
  },
  paypalWord: {
    fontSize: 18,
    fontWeight: '700',
    color: '#009CDE',
  },
  emptyRoot: {
    flex: 1,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  emptyArt: {
    width: 100,
    height: 100,
    borderRadius: 6,
    backgroundColor: '#E3F2FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textDark,
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 8,
    textAlign: 'center',
    fontSize: 15,
    color: cartColors.muted,
    lineHeight: 22,
  },
  emptyLink: {
    marginTop: 20,
    fontSize: 15,
    fontWeight: '600',
    color: cartColors.linkBlue,
    textDecorationLine: 'underline',
  },
});
