import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  content: {
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.textDark,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#6C7A91',
  },
  clearAll: {
    color: colors.headerBlue,
    fontSize: 14,
    fontWeight: '700',
  },
  freeShipCard: {
    backgroundColor: '#EAF7FF',
    borderWidth: 1,
    borderColor: '#C6E8FA',
    borderRadius: 14,
    padding: 12,
    marginBottom: 14,
  },
  freeShipTitle: {
    color: '#0D4F73',
    fontWeight: '700',
    marginBottom: 8,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#CFE8F8',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.headerBlue,
    borderRadius: 999,
  },
  lineCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
  },
  lineImage: {
    width: 92,
    height: 92,
    borderRadius: 12,
    backgroundColor: '#EEF2F5',
  },
  lineBody: {
    flex: 1,
    marginLeft: 12,
  },
  lineTitle: {
    fontSize: 14,
    color: colors.textDark,
    fontWeight: '700',
  },
  lineVariant: {
    marginTop: 4,
    fontSize: 12,
    color: '#64748B',
  },
  inventory: {
    marginTop: 2,
    fontSize: 12,
    color: '#0F9D58',
    fontWeight: '600',
  },
  lineBottomRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    color: colors.textDark,
    fontWeight: '800',
    fontSize: 16,
  },
  compareAt: {
    marginTop: 2,
    color: '#8A94A6',
    fontSize: 12,
    textDecorationLine: 'line-through',
  },
  quantityWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D8E0EB',
    borderRadius: 999,
    paddingHorizontal: 4,
    height: 34,
  },
  qtyBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyValue: {
    minWidth: 20,
    textAlign: 'center',
    fontWeight: '700',
    color: colors.textDark,
  },
  lineActions: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 14,
  },
  actionText: {
    color: colors.headerBlue,
    fontSize: 13,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    padding: 14,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textDark,
    marginBottom: 10,
  },
  codeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  codeInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D8E0EB',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 42,
    color: colors.textDark,
    backgroundColor: '#FAFCFF',
  },
  applyBtn: {
    height: 42,
    borderRadius: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.headerBlue,
  },
  applyText: {
    color: colors.white,
    fontWeight: '700',
  },
  codeMessage: {
    marginTop: 8,
    color: '#475569',
    fontSize: 12,
  },
  noteInput: {
    minHeight: 72,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#D8E0EB',
    borderRadius: 10,
    padding: 10,
    color: colors.textDark,
    backgroundColor: '#FAFCFF',
  },
  sumRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sumLabel: {
    color: '#55637B',
  },
  sumValue: {
    color: colors.textDark,
    fontWeight: '600',
  },
  sumSavings: {
    color: '#0F9D58',
    fontWeight: '700',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#E4EAF2',
    paddingTop: 10,
    marginTop: 4,
    marginBottom: 0,
  },
  totalLabel: {
    color: colors.textDark,
    fontWeight: '800',
    fontSize: 16,
  },
  totalValue: {
    color: colors.textDark,
    fontWeight: '900',
    fontSize: 18,
  },
  checkoutBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: '#DEE7F1',
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkoutLabel: {
    color: '#64748B',
    fontSize: 12,
  },
  checkoutTotal: {
    marginTop: 2,
    color: colors.textDark,
    fontSize: 20,
    fontWeight: '900',
  },
  checkoutBtn: {
    backgroundColor: colors.headerBlue,
    borderRadius: 999,
    paddingHorizontal: 24,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkoutText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 16,
  },
  emptyRoot: {
    flex: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyTitle: {
    marginTop: 12,
    fontSize: 24,
    color: colors.textDark,
    fontWeight: '800',
  },
  emptyText: {
    marginTop: 8,
    textAlign: 'center',
    color: '#64748B',
    lineHeight: 20,
  },
});
