import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  content: {
    paddingBottom: 32,
  },
  stickyHeader: {
    zIndex: 200,
    elevation: 200,
  },
  loadingScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 24,
  },
  loadingText: {
    color: colors.textLabel,
    fontSize: 15,
    fontWeight: '500',
    textAlign: 'center',
  },
  notificationOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.48)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  notificationCard: {
    width: '100%',
    maxWidth: 900,
    minHeight: 420,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#F7F7F8',
    paddingHorizontal: 24,
    paddingTop: 74,
    paddingBottom: 36,
    alignItems: 'center',
  },
  notificationPatternLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  notificationPatternBlob: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.05)',
  },
  notificationPatternBlobOne: {
    width: 220,
    height: 220,
    left: -55,
    top: 44,
  },
  notificationPatternBlobTwo: {
    width: 240,
    height: 240,
    right: -80,
    top: 34,
  },
  notificationPatternBlobThree: {
    width: 250,
    height: 250,
    left: -70,
    bottom: -70,
  },
  notificationPatternBlobFour: {
    width: 300,
    height: 300,
    right: -120,
    bottom: -120,
  },
  notificationCloseBtn: {
    position: 'absolute',
    right: 14,
    top: 14,
    zIndex: 4,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1F2937',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationCloseText: {
    color: '#FFFFFF',
    fontSize: 28,
    lineHeight: 30,
    fontWeight: '300',
    marginTop: -1,
  },
  notificationTitle: {
    color: '#111827',
    textAlign: 'center',
    fontSize: 32,
    fontWeight: '600',
    lineHeight: 40,
    maxWidth: 760,
    zIndex: 2,
  },
  notificationSubtitle: {
    marginTop: 26,
    color: '#232C3B',
    fontSize: 22,
    lineHeight: 34,
    textAlign: 'center',
    maxWidth: 760,
    zIndex: 2,
  },
  notificationInputRow: {
    marginTop: 34,
    width: '100%',
    maxWidth: 520,
    height: 50,
    borderRadius: 31,
    overflow: 'hidden',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#E6E9EE',
    backgroundColor: '#FFFFFF',
    zIndex: 2,
  },
  notificationInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: 22,
    color: '#6B7280',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
  },
  notificationSubmitBtn: {
    minWidth: 150,
    paddingHorizontal: 26,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationSubmitText: {
    color: '#FFFFFF',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '300',
  },
});
