import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 36,
    paddingBottom: 26,
    gap: 14,
  },
  heroCard: {
    borderRadius: 22,
    padding: 18,
    overflow: 'hidden',
  },
  heroTag: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  heroTagText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  heroTitle: {
    marginTop: 10,
    color: colors.white,
    fontSize: 27,
    lineHeight: 33,
    fontWeight: '800',
  },
  heroSubtitle: {
    marginTop: 7,
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 14,
    lineHeight: 20,
  },
  countdownRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 8,
  },
  countdownChip: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    minWidth: 62,
  },
  countdownValue: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  countdownLabel: {
    color: 'rgba(255, 255, 255, 0.82)',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 2,
  },
  sectionCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 14,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#18212f',
    fontSize: 18,
    fontWeight: '800',
  },
  sectionMeta: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  spotlightRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 10,
  },
  spotlightIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spotlightTextWrap: {
    flex: 1,
  },
  spotlightTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  spotlightDesc: {
    marginTop: 4,
    color: '#5b6472',
    fontSize: 13,
    lineHeight: 18,
  },
  ctaRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
  },
  primaryBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: '#111827',
  },
  primaryBtnText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
  },
  secondaryBtnText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  giftGrid: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  giftCard: {
    width: '48.3%',
    borderRadius: 14,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    minHeight: 112,
  },
  giftLabel: {
    marginTop: 8,
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  giftSub: {
    marginTop: 4,
    color: '#64748b',
    fontSize: 12,
  },
  fashionNoteCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ddd6fe',
    backgroundColor: '#f5f3ff',
    padding: 14,
  },
  fashionNoteTitle: {
    color: '#4c1d95',
    fontSize: 15,
    fontWeight: '800',
  },
  fashionNoteText: {
    marginTop: 6,
    color: '#5b21b6',
    fontSize: 13,
    lineHeight: 18,
  },
});
