import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  content: {
    padding: 16,
  },
  galleryWrap: {
    marginBottom: 14,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: colors.white,
  },
  galleryImageArea: {
    height: 320,
    position: 'relative',
    backgroundColor: colors.white,
  },
  galleryImage: {
    width: '100%',
    height: 320,
    backgroundColor: colors.white,
  },
  galleryHeartBtn: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  imageViewerRoot: {
    flex: 1,
    backgroundColor: '#000',
  },
  imageViewerList: {
    flex: 1,
  },
  imageViewerPage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000',
  },
  imageViewerImage: {
    width: '100%',
    height: '100%',
  },
  imageViewerClose: {
    position: 'absolute',
    zIndex: 2,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    backgroundColor: colors.white,
  },
  galleryDot: {
    height: 4,
    borderRadius: 2,
  },
  galleryDotActive: {
    width: 22,
    backgroundColor: colors.headerBlue,
  },
  galleryDotInactive: {
    width: 6,
    backgroundColor: '#D8E0EB',
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    padding: 14,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingText: {
    color: colors.textDark,
    fontWeight: '700',
    marginRight: 8,
  },
  badgePill: {
    backgroundColor: '#2FB47C',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 12,
  },
  title: {
    marginTop: 10,
    fontSize: 22,
    fontWeight: '700',
    color: colors.textDark,
    lineHeight: 30,
  },
  priceRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 10,
  },
  oldPrice: {
    color: '#8A94A6',
    textDecorationLine: 'line-through',
    fontWeight: '600',
  },
  newPrice: {
    color: '#E11D48',
    fontSize: 28,
    fontWeight: '900',
  },
  qtyRow: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  qtyLabel: {
    fontSize: 16,
    color: colors.textDark,
    fontWeight: '700',
  },
  quantityWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D8E0EB',
    borderRadius: 6,
    paddingHorizontal: 4,
    height: 36,
  },
  qtyBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyValue: {
    minWidth: 24,
    textAlign: 'center',
    fontWeight: '700',
    color: colors.textDark,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: '#DEE7F1',
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  addBtn: {
    alignSelf: 'stretch',
    height: 46,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.headerBlue,
  },
  addBtnText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 16,
  },
  railBleed: {
    marginHorizontal: -16,
  },
  subsectionCard: {
    marginTop: 14,
    backgroundColor: colors.white,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    padding: 14,
  },
  subsectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textDark,
    marginBottom: 10,
  },
  aboutSection: {
    marginTop: 14,
  },
  aboutSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textDark,
    marginBottom: 12,
  },
  aboutCard: {
    backgroundColor: colors.white,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    overflow: 'hidden',
  },
  descriptionAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 16,
  },
  descriptionAccordionHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(15,23,42,0.08)',
  },
  descriptionAccordionLabel: {
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    color: '#3D4555',
    paddingRight: 12,
  },
  descriptionAccordionChevron: {
    marginLeft: 8,
  },
  descriptionAccordionExpanded: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
  },
  descriptionBlockTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#3D4555',
    marginBottom: 12,
  },
  descriptionBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    gap: 10,
  },
  descriptionBulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4B5565',
    marginTop: 8,
  },
  descriptionBulletText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: '#5C667A',
    fontWeight: '500',
  },
  subsectionBody: {
    fontSize: 15,
    lineHeight: 22,
    color: '#4B5565',
    fontWeight: '500',
  },
  reviewsSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(15,23,42,0.08)',
  },
  reviewsAverageWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 52,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(36,114,169,0.1)',
  },
  reviewsAverage: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.headerBlue,
  },
  reviewsMeta: {
    flex: 1,
    gap: 6,
  },
  reviewsBasedOn: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5C667A',
  },
  reviewItem: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(15,23,42,0.06)',
  },
  reviewItemFirst: {
    marginTop: 0,
    paddingTop: 0,
    borderTopWidth: 0,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewAuthor: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
  },
  reviewDate: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8A94A6',
  },
  reviewStarsRow: {
    flexDirection: 'row',
    gap: 2,
    marginBottom: 6,
  },
  reviewText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#4B5565',
    fontWeight: '500',
  },
});
