import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.white,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.08)',
    paddingHorizontal: 14,
    paddingBottom: 14,
    overflow: 'hidden',
    justifyContent: 'flex-start',
  },
  imageArea: {
    marginTop: 0,
    borderRadius: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.03)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  imagePlaceholder: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImage: {
    width: '96%',
    height: '92%',
  },
  heartCircle: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  plusCircle: {
    position: 'absolute',
    right: 12,
    bottom: 18,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.headerBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  savePill: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: '#E11D48',
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: '100%',
  },
  saveText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 16,
  },
  titleWrap: {
    marginTop: 10,
    color: colors.textDark,
  },
  title: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 20,
  },
  priceRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
  },
  oldPrice: {
    color: '#E11D48',
    fontWeight: '800',
    textDecorationLine: 'line-through',
    fontSize: 16,
  },
  newPrice: {
    color: '#E11D48',
    fontWeight: '900',
    fontSize: 20,
  },
  bottomRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  badgePill: {
    backgroundColor: '#2FB47C',
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 14,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    color: colors.textLabel,
    fontWeight: '600',
    fontSize: 14,
  },
});
