import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  content: {
    padding: 16,
  },
  galleryWrap: {
    marginBottom: 14,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: colors.white,
  },
  galleryImage: {
    width: '100%',
    height: 320,
    backgroundColor: colors.white,
  },
  galleryDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    backgroundColor: colors.white,
  },
  galleryDot: {
    height: 4,
    borderRadius: 2,
  },
  galleryDotActive: {
    width: 22,
    backgroundColor: colors.headerBlue,
  },
  galleryDotInactive: {
    width: 6,
    backgroundColor: '#D8E0EB',
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    padding: 14,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingText: {
    color: colors.textDark,
    fontWeight: '700',
    marginRight: 8,
  },
  badgePill: {
    backgroundColor: '#2FB47C',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 12,
  },
  title: {
    marginTop: 10,
    fontSize: 22,
    fontWeight: '700',
    color: colors.textDark,
    lineHeight: 30,
  },
  savePill: {
    marginTop: 12,
    alignSelf: 'flex-start',
    backgroundColor: '#E11D48',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  saveText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 12,
  },
  priceRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 10,
  },
  oldPrice: {
    color: '#8A94A6',
    textDecorationLine: 'line-through',
    fontWeight: '600',
  },
  newPrice: {
    color: '#E11D48',
    fontSize: 28,
    fontWeight: '900',
  },
  qtyRow: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  qtyLabel: {
    fontSize: 16,
    color: colors.textDark,
    fontWeight: '700',
  },
  quantityWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D8E0EB',
    borderRadius: 999,
    paddingHorizontal: 4,
    height: 36,
  },
  qtyBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyValue: {
    minWidth: 24,
    textAlign: 'center',
    fontWeight: '700',
    color: colors.textDark,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: '#DEE7F1',
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  addBtn: {
    alignSelf: 'stretch',
    height: 46,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.headerBlue,
  },
  addBtnText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 16,
  },
});
